spring.datasource.url=jdbc:mysql://localhost:3306/shopify
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.security.user.name=customuser
spring.security.user.password=custompassword